services:
  frontend:
    build:
      context: ./new_front
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./Backend/app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENV=production